Repository ASFHyP3/asf-tools, pull requests merged in 2020-12, with the labels that each got.

#40 Simplify EPSG find and always handle antimerridian
  .github/workflows/static-analysis.yml
  asf_tools/composite.py
  tests/test_composite.py
Labels: bumpless

#42 better handling of output file names
  asf_tools/composite.py
Labels: bumpless

#47 Reduce memory burden
  asf_tools/composite.py
Labels: bumpless

#44 add overviews to output tifs
  asf_tools/composite.py
Labels: bumpless

#48 use AVERAGE overview resampling for better nodata handling
  asf_tools/composite.py
Labels: bumpless

#49 Logging improvements
  asf_tools/composite.py
Labels: bumpless

#51 require gdal>=3.2.0 for COG driver and OVERVIEW_RESAMPLING
  conda-env.yml
  setup.py
Labels: bumpless

#53 send logs to stdout, reduce number of log.info messages
  asf_tools/composite.py
Labels: bumpless

#52 CLI improvements
  asf_tools/composite.py
Labels: bumpless

#54 convert double quotes to single quotes
  asf_tools/composite.py
Labels: bumpless

#55 add epsg_to_wkt helper funtion
  asf_tools/composite.py
  tests/test_composite.py
Labels: bumpless

#56 Use David Small's language for composite tool
  asf_tools/composite.py
Labels: bumpless

#58 fix indent in write_cog()
  asf_tools/composite.py
Labels: bumpless

#57 add usage draft to asf_tools readme
  CHANGELOG.md
  asf_tools/README.md
  setup.py
  tests/test_entrypoints.py
Labels: bumpless

#60 add test for write_cog()
  tests/test_composite.py
Labels: bumpless

#59 add test for get_full_extents()
  tests/test_composite.py
Labels: bumpless

#61 add test for make_composite
  tests/test_composite.py
Labels: bumpless

#62 Added usage tip and LRW explanation
  asf_tools/README.md
Labels: bumpless

#63 edit asftools readme for gitsnippet preparation
  README.md
  asf_tools/README.md
Labels: bumpless, documentation

#64 add missing docstrings
  asf_tools/composite.py
Labels: bumpless

#66 Release: v0.2.0 with asf_tools package
  .github/PULL_REQUEST_TEMPLATE/release.md
  .github/pull_request_template.md
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag.yml
  .github/workflows/test-and-build.yml
  ArcGIS-toolbox/ASF_Tools.pyt
  CHANGELOG.md
  MANIFEST.in
  README.md
  asf_tools/README.md
  asf_tools/__init__.py
  asf_tools/composite.py
  conda-env.yml
  pyproject.toml
  setup.py
  tests/conftest.py
  tests/test_composite.py
  tests/test_entrypoints.py
  tests/test_version.py
Labels: minor

#67 Fix release workflow
  .github/workflows/tag.yml
  .github/workflows/test-and-build.yml
Labels: bug, bumpless

#68 Add DOI to READMEs
  ArcGIS-toolbox/README.md
  README.md
  asf_tools/README.md
Labels: bumpless

#69 Update README and hyp3-docs workflow
  .github/workflows/release.yml
  asf_tools/README.md
  asf_tools/composite.py
Labels: bumpless, documentation
