Repository ASFHyP3/asf-tools, pull requests merged in 2020-10, with the labels that each got.

#17 Merge Code Cleanup branch
  ArcGIS-toolbox/ASF_Tools.pyt
Labels: bumpless

#19 Release version including RGB Decomposition Tool
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/release.md
  .github/pull_request_template.md
  .github/queries/asssociated-pr.query.yml
  .github/queries/pr-labels.query.yml
  .github/workflows/changelog.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag.yml
  .gitignore
  .gitleaks.toml
  .trufflehog.txt
  ArcGIS-toolbox/ASF_Tools.LogDiff.pyt.xml
  ArcGIS-toolbox/ASF_Tools.RGBDecomp.pyt.xml
  ArcGIS-toolbox/ASF_Tools.ReclassifyRTC.pyt.xml
  ArcGIS-toolbox/ASF_Tools.ScaleConversion.pyt.xml
  ArcGIS-toolbox/ASF_Tools.UnzipFiles.pyt.xml
  ArcGIS-toolbox/ASF_Tools.pyt
  ArcGIS-toolbox/ASF_Tools.pyt.xml
  ArcGIS-toolbox/README.md
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  README.md
  conda-env.yml
Labels: minor

#20 Fix building the Arc toolbox zip name
  .github/workflows/release.yml
Labels: CI/CD, bumpless

#21 make link a hyperlink
  README.md
Labels: bumpless

#22 Add language and links for On-Demand RTC Processing in Vertex
  ArcGIS-toolbox/README.md
Labels: bumpless

#23 Add references to On Demand Products in xml files
  ArcGIS-toolbox/ASF_Tools.LogDiff.pyt.xml
  ArcGIS-toolbox/ASF_Tools.RGBDecomp.pyt.xml
  ArcGIS-toolbox/ASF_Tools.ScaleConversion.pyt.xml
  ArcGIS-toolbox/ASF_Tools.UnzipFiles.pyt.xml
  ArcGIS-toolbox/ASF_Tools.pyt.xml
Labels: bumpless

#24 Add info and links for On Demand RTC
  .github/workflows/release.yml
  ArcGIS-toolbox/ASF_Tools.LogDiff.pyt.xml
  ArcGIS-toolbox/ASF_Tools.RGBDecomp.pyt.xml
  ArcGIS-toolbox/ASF_Tools.ScaleConversion.pyt.xml
  ArcGIS-toolbox/ASF_Tools.UnzipFiles.pyt.xml
  ArcGIS-toolbox/ASF_Tools.pyt.xml
  ArcGIS-toolbox/README.md
  CHANGELOG.md
  README.md
Labels: patch

#25 Trigger rebuild of HyP3 docs to pull in current release
  .github/workflows/release.yml
Labels: CI/CD, bumpless
