Repository ASFHyP3/asf-tools, pull requests merged in 2022-07, with the labels that each got.

#131 change logstat function to isclose
  tests/test_flood_map.py
Labels: bumpless

#132 Update workflow
  .github/workflows/static-analysis.yml
Labels: bumpless

#133 Prevent flood depths from being calculated in an S1 scene's no-data values.
  CHANGELOG.md
  asf_tools/flood_map.py
  environment.yml
  setup.py
  tests/test_flood_map.py
Labels: bug

#134 Release v0.4.2
  CHANGELOG.md
  asf_tools/flood_map.py
  asf_tools/hand/calculate.py
  environment.yml
  setup.py
  tests/test_flood_map.py
Labels: patch
