Repository ASFHyP3/asf-tools, pull requests merged in 2022-03, with the labels that each got.

#96 Release v0.3.1 -- Docker image
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
  .github/workflows/test-and-tag.yml
  CHANGELOG.md
  Dockerfile
  asf_tools/README.md
  asf_tools/water_map.py
  tests/test_water_map.py
Labels: patch

#101 Use nanpercentile to fix #99
  CHANGELOG.md
  asf_tools/water_map.py
  environment.yml
Labels: bug

#102 Release v0.3.2
  CHANGELOG.md
  asf_tools/water_map.py
Labels: patch

#106 Bugfix: vsi paths to calculate_hand entrypoint
  CHANGELOG.md
  asf_tools/hand/calculate.py
Labels: bug

#107 Release v0.3.3
  CHANGELOG.md
  asf_tools/hand/calculate.py
  environment.yml
  setup.py
Labels: patch

#111 Save depth rasters as floats
  asf_tools/flood_map.py
Labels: bumpless
