Repository ASFHyP3/asf-tools, pull requests merged in 2023-01, with the labels that each got.

#154 uniform 'ing's
  src/asf_tools/hand/calculate.py
Labels: bumpless, documentation

#161 Release v0.4.5: Update directory structure and switch to pyproject.toml
  .github/workflows/changelog.yml
  .github/workflows/distribute.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  MANIFEST.in
  README.md
  environment.yml
  pyproject.toml
  setup.py
  src/asf_tools/README.md
  src/asf_tools/__init__.py
  src/asf_tools/composite.py
  src/asf_tools/data/water_extent.vrt
  src/asf_tools/dem.py
  src/asf_tools/flood_map.py
  src/asf_tools/hand/__init__.py
  src/asf_tools/hand/calculate.py
  src/asf_tools/hand/prepare.py
  src/asf_tools/raster.py
  src/asf_tools/threshold.py
  src/asf_tools/tile.py
  src/asf_tools/util.py
  src/asf_tools/vector.py
  src/asf_tools/water_map.py
Labels: patch

#164 provide token to dispatch action
  .github/workflows/release.yml
Labels: bug, bumpless

#165 remove setup.py reference and unnecessary error message
  src/asf_tools/__init__.py
Labels: bumpless

#166 Update ArcGIS Toolbox metadata
  .github/workflows/changelog.yml
  .github/workflows/distribute.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
  ArcGIS-toolbox/ASF_Tools.LogDiff.pyt.xml
  ArcGIS-toolbox/ASF_Tools.RGBDecomp.pyt.xml
  ArcGIS-toolbox/ASF_Tools.ScaleConversion.pyt.xml
  ArcGIS-toolbox/ASF_Tools.UnzipFiles.pyt.xml
  ArcGIS-toolbox/ASF_Tools.pyt.xml
  CHANGELOG.md
Labels: patch

#168 Release 0.4.6 - ArcGIS Toolbox Updates
  .github/workflows/changelog.yml
  .github/workflows/distribute.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
  ArcGIS-toolbox/ASF_Tools.LogDiff.pyt.xml
  ArcGIS-toolbox/ASF_Tools.RGBDecomp.pyt.xml
  ArcGIS-toolbox/ASF_Tools.ScaleConversion.pyt.xml
  ArcGIS-toolbox/ASF_Tools.UnzipFiles.pyt.xml
  ArcGIS-toolbox/ASF_Tools.pyt.xml
  CHANGELOG.md
  src/asf_tools/__init__.py
Labels: patch

#171 Fix water_map and flood_map zip paths
  src/asf_tools/flood_map.py
  src/asf_tools/water_map.py
Labels: bug, bumpless
